### ISSUE TITLE
Loading yii2-user views on windows problem

### ISSUE THREAD

**Issue by draskoi** [phundament/app#140]
There is a problem in Windows enviroment, where 

preg_match('|(/[^/]*/[^/]*\.php)$|', __FILE__, $matches) 
require(Yii::getAlias('@dektrium/user/views/' . $matches[1]));

doesn't parse controller/action out of the box.
So for C:\xampp\htdocs\app\views\user\security\login.php, you get empty $matches.

The problem is in 
views/user/security/login/php
views/user/registration/finish.php
views/user/registration/resend.php

**Comment by schmunk42** [comment]
Thanks, we'll check that on Windows.

**Comment by undigo** [comment]
hi,
I have the same problem on windows environment.
can you send me your best way to by pass this, use on unix env only or this pb will be fixed in how many weeks ?

thks in advance,
UF.

**Comment by schmunk42** [comment]
@Dletz could you please try to reproduce this

**Comment by Konrad90** [comment]
fixed with https://github.com/phundament/app/pull/155

**Comment by schmunk42** [comment]
@undigo #155 has been merged to master, please apply the fix manually in existing projects.

@Konrad90 I think we should apply the fix here also: https://github.com/dmstr/yii2-adminlte-asset/tree/master/example-views/phundament/app - could you create a PR
