### ISSUE TITLE
translate module

### ISSUE THREAD

**Issue by philippfrenzel** [phundament/app#141]
Hi, what do you think about adding:

"lajax/yii2-translate-manager": "1.*",
"ivanovyordan/yii2-migration": "*"

makes translations managable;)

cheers philipp

**Comment by schmunk42** [comment]
Thanks.
But why do you need the migration module?

**Comment by philippfrenzel** [comment]
it just manager to execute the latest migrates after a composer update is done... so for deployment I can ensure that it's for sure getting applied... but can be done by a shell script although... maybe to much of an overkill here?

**Comment by schmunk42** [comment]
We have that feature for a while: https://github.com/dmstr/yii2-migrate-command see the README how to use it.
Is also planned to be implemented into `yiisoft/yii2` https://github.com/yiisoft/yii2/issues/384

**Comment by philippfrenzel** [comment]
ok, thanks! I didn't see the "post-update-command" -> Thanks! what about the translate stuff?

**Comment by schmunk42** [comment]
We have to evaluate this. But in the meantime you can add the module to your Phundament or Yii app as usual.

**Comment by philippfrenzel** [comment]
Thanks i did and sadly the Scanner has an issue:(

**Comment by Quexer69** [comment]
the "lajax/yii2-translate-manager" looks great!

What do you mean with scanner?

**Comment by philippfrenzel** [comment]
They are using a scanner for database and filebased translations which works fine on my local machine, but on my 1und1 managed server, missing the i18n module for php it fails... so actually I would not say it's the modules fault more the hosters issue...

**Comment by schmunk42** [comment]
@philippfrenzel The scanner sounds nice, we had that for Yii 1 also, but it was not very fast.
You could create a migration on your dev machine with the initial scanned data or can't you run migrations at all?

Updates of the scanned data could be tricky, though. But would be manageable if the scanner could add a flag to the record, but I haven't looked at the code yet.

**Comment by philippfrenzel** [comment]
well, the setup of the translate module works all fine and the scanner on my local machine works although fine... The scanner really takes quit a lot of time but as this is no job that needs to be done in realtime :) I don't care of performance... well would need to if it takes longer than max execution time...  so the author of the suggested translate module figured out what the issue is with the error and said he wants to fix it within the next couple of days...

btw. I love the ph4 template!

**Comment by osCMattiFinn** [comment]
I have successfully ported my Yii Tranlsation Behavior class to Yii2: http://www.yiiframework.com/extension/yii-language-behavior/

I don't however have the time to clean it up and write all the code required for adding it with Composer.

This class works very nicely and makes creating a multi lingual app very easy.

You may consider porting it yourself to Phundament.

**Comment by schmunk42** [comment]
lajax is part for a while now.

@osCMattiFinn Do you have a link to a yii2 behavior?
