### ISSUE TITLE
Error with composer

### ISSUE THREAD

**Issue by Migo2468** [phundament/app#142]
When I try to install with composer, in ssh of my server. I have some errors: 

ssh> php composer.phar global require "fxp/composer-asset-plugin:1.0.0-beta
4"
Changed current directory to /var/services/homes/admin/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing fxp/composer-asset-plugin (v1.0.0)
  - Installing fxp/composer-asset-plugin (v1.0.0-beta4)
    Downloading: 100%         

Writing lock file
Generating autoload files

ssh> php composer.phar create-project --stability=beta phundament/app
Installing phundament/app (4.0.0-beta9)
  - Installing phundament/app (4.0.0-beta9)
    Loading from cache

Created project in /volume1/web/Migo/advanced/app
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing yiisoft/yii2-composer (2.0.2)
    Loading from cache

  - Installing bower-asset/jquery (2.1.3)
    Loading from cache

  - Installing bower-asset/bootstrap (v3.3.1)
    Loading from cache

  - Installing bower-asset/jquery.inputmask (3.1.55)
    Loading from cache

  - Installing bower-asset/punycode (v1.3.2)
    Loading from cache

  - Installing bower-asset/yii2-pjax (v2.0.2)
    Loading from cache

  - Installing ezyang/htmlpurifier (v4.6.0)
    Loading from cache

  - Installing cebe/markdown (1.0.1)
    Loading from cache

  - Installing yiisoft/yii2 (2.0.2)
    Loading from cache

  - Installing swiftmailer/swiftmailer (v5.3.1)
    Loading from cache

  - Installing yiisoft/yii2-swiftmailer (2.0.2)
    Loading from cache

  - Installing yiisoft/yii2-authclient (2.0.2)
    Loading from cache

  - Installing dektrium/yii2-user (v0.9.1)
    Loading from cache

  - Installing yiisoft/yii2-bootstrap (2.0.2)
    Loading from cache

  - Installing cebe/yii2-gravatar (1.1)
    Loading from cache

  - Installing bower-asset/font-awesome (v4.2.0)
    Loading from cache

  - Installing bower-asset/admin-lte (1.3)
    Loading from cache

  - Installing dmstr/yii2-adminlte-asset (0.1.0)
    Loading from cache

  - Installing dmstr/yii2-app-command (dev-master 99ad4f5)
    <b>Cloning 99ad4f5fc5227aa3415b20b991deda6254e65a5f
    Failed to download dmstr/yii2-app-command from source: Failed to clone git@github.com:dmstr/yii2-app-command.git, git was not found, check that it is installed and in your PATH env.

sh: git: not found</b>

    Now trying to download from dist
  - Installing dmstr/yii2-app-command (dev-master 99ad4f5)
    Loading from cache

  - Installing dmstr/yii2-log (dev-master 8fc081b)
    <b>Cloning 8fc081bf19f8a0ab8bcbd450b4aaf99d6c9abfc1
    Failed to download dmstr/yii2-log from source: Failed to clone git@github.com:dmstr/yii2-log.git, git was not found, check that it is installed and in your PATH env.

sh: git: not found</b>

    Now trying to download from dist
  - Installing dmstr/yii2-log (dev-master 8fc081b)
    Loading from cache

  - Installing dmstr/yii2-migrate-command (0.1.0)
    Loading from cache

  - Installing symfony/event-dispatcher (v2.6.3)
    Loading from cache

  - Installing guzzle/guzzle (v3.8.1)
    Loading from cache

  - Installing mikehaertl/php-shellcommand (1.0.4)
    Loading from cache

  - Installing schmunk42/yii2-markdocs-module (dev-master 8fd52a1)
    Cloning 8fd52a17fa91d2f184e3896196a479a347d9cca2

                                                                               
  <b>[RuntimeException]                                                           
  Failed to clone git@github.com:schmunk42/yii2-markdocs-module.git, git was   
  not found, check that it is installed and in your PATH env.                  
  sh: git: not found</b>                                                           
                                                                               

create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]

Any suggestions?

**Comment by Quexer69** [comment]
I'am wondering why its trying to clone via ssh ? Are you on a server or VM ?

all repo URLs in the composer.lock files are  as `https://github.com/...` and not as `git@github.com:...` !?

what are these commands doing ? stability **dev** or **stable**, instead of **beta** ->

`php composer.phar create-project --stability=dev phundament/app`
or
`php composer.phar create-project --stability=stable phundament/app`

or try to 
`git clone https://github.com/phundament/app.git my-app` 
and then
` php composer.phar install --prefer-dist`

**Comment by Migo2468** [comment]
Why ssh, because I have a NAS synology I this is the only way to use composer. 

When I try:
php composer.phar global require "fxp/composer-asset-plugin:1.0.0-beta4"
and:
php composer.phar create-project --stability=dev phundament/app

It's work

**Comment by Migo2468** [comment]
Thank you, the rest of the installation with no problem.

**Comment by Quexer69** [comment]
you are welcome :-)
