### ISSUE TITLE
login error after clean install

### ISSUE THREAD

**Issue by carnao** [phundament/app#149]
Hello i did  a fresh install on windows, xampp server, php 5.6 but after installation and migration i can open the frontend  page but when i try to login i got the following error, can someone help find the problem?

PHP Compile Error – yii\base\ErrorException

main(): Failed opening required 'C:\xampp2\htdocs\hydra2\app\vendor/dektrium/yii2-user/views/' (include_path='.;C:\xampp2\php\PEAR')
1. in C:\xampp2\htdocs\hydra2\app\views\user\security\login.php at line 6
123456<?php
 
$this->context->layout = '@app/views/layouts/main';
 
preg_match('|(/[^/]*/[^/]*\.php)$|', __FILE__, $matches);
require(Yii::getAlias('@dektrium/user/views/' . $matches[1]));
2. yii\base\ErrorHandler::handleFatalError()
$_GET = [
    'r' => 'user/security/login',
];

$_SERVER = [
    'MIBDIRS' => 'C:/xampp2/php/extras/mibs',
    'MYSQL_HOME' => '\\xampp\\mysql\\bin',
    'OPENSSL_CONF' => 'C:/xampp2/apache/bin/openssl.cnf',
    'PHP_PEAR_SYSCONF_DIR' => '\\xampp\\php',
    'PHPRC' => '\\xampp\\php',
    'TMP' => '\\xampp\\tmp',
    'HTTP_HOST' => 'localhost',
    'HTTP_CONNECTION' => 'keep-alive',
    'HTTP_ACCEPT' => 'text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8',
    'HTTP_USER_AGENT' => 'Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.111 Safari/537.36',
    'HTTP_REFERER' => 'http://localhost/hydra2/app/web/index.php?r=user%2Fregistration%2Fregister',
    'HTTP_ACCEPT_ENCODING' => 'gzip, deflate, sdch',
    'HTTP_ACCEPT_LANGUAGE' => 'en-US,en;q=0.8,it;q=0.6',
    'HTTP_COOKIE' => 'PHPSESSID=efec57rgq0mb0iuej03ag2jul4; _csrf=adcc29e0230b25495de07b3683ecb41b117ef66e18cbca2022857334d869bb85s%3A32%3A%223p0ykYBVp-8_gQdCW2bZiWZYwJtaLnq1%22%3B',
    'PATH' => 'C:\\Windows\\system32;C:\\Windows;C:\\Windows\\System32\\Wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;D:\\adt-bundle-windows-x86_64\\sdk\\platform-tools;D:\\adt-bundle-windows-x86_64\\sdk\\tools;D:\\apache-ant-1.8.4\\bin;C:\\Program Files\\Java\\jdk1.7.0_11\\bin;C:\\xampp\\php;C:\\Program Files\\Oracle\\VirtualBox;C:\\xampp2\\php;C:\\Program Files (x86)\\Git\\cmd;C:\\Program Files (x86)\\GitExtensions\\;C:\\Program Files (x86)\\nodejs\\;C:\\Program Files\\TortoiseSVN\\bin;C:\\ProgramData\\ComposerSetup\\bin;C:\\Program Files (x86)\\OpenVPN\\bin;C:\\Users\\luca\\AppData\\Roaming\\npm',
    'SystemRoot' => 'C:\\Windows',
    'COMSPEC' => 'C:\\Windows\\system32\\cmd.exe',
    'PATHEXT' => '.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC',
    'WINDIR' => 'C:\\Windows',
    'SERVER_SIGNATURE' => '
Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3 Server at localhost Port 80

',
    'SERVER_SOFTWARE' => 'Apache/2.4.10 (Win32) OpenSSL/1.0.1i PHP/5.6.3',
    'SERVER_NAME' => 'localhost',
    'SERVER_ADDR' => '::1',
    'SERVER_PORT' => '80',
    'REMOTE_ADDR' => '::1',
    'DOCUMENT_ROOT' => 'C:/xampp2/htdocs',
    'REQUEST_SCHEME' => 'http',
    'CONTEXT_PREFIX' => '',
    'CONTEXT_DOCUMENT_ROOT' => 'C:/xampp2/htdocs',
    'SERVER_ADMIN' => 'postmaster@localhost',
    'SCRIPT_FILENAME' => 'C:/xampp2/htdocs/hydra2/app/web/index.php',
    'REMOTE_PORT' => '52155',
    'GATEWAY_INTERFACE' => 'CGI/1.1',
    'SERVER_PROTOCOL' => 'HTTP/1.1',
    'REQUEST_METHOD' => 'GET',
    'QUERY_STRING' => 'r=user%2Fsecurity%2Flogin',
    'REQUEST_URI' => '/hydra2/app/web/index.php?r=user%2Fsecurity%2Flogin',
    'SCRIPT_NAME' => '/hydra2/app/web/index.php',
    'PHP_SELF' => '/hydra2/app/web/index.php',
    'REQUEST_TIME_FLOAT' => 1423864771.9059998989105224609375,
    'REQUEST_TIME' => 1423864771,
    'YII_DEBUG' => 'true',
    'YII_ENV' => 'dev',
    'YII_TRACE_LEVEL' => '',
    'APP_NAME' => 'webmatrix',
    'APP_ADMIN_EMAIL' => '--------------',
    'APP_ADMIN_PASSWORD' => 'admin',
    'APP_SUPPORT_EMAIL' => '--------------',
    'APP_COOKIE_VALIDATION_KEY' => 'changeme2',
    'APP_COPYRIGHT' => '',
    'APP_PRETTY_URLS' => '',
    'DB_PORT_3306_TCP_ADDR' => 'localhost',
    'DB_PORT_3306_TCP_PORT' => '3306',
    'DB_ENV_MYSQL_DATABASE' => 'test',
    'DB_ENV_MYSQL_USER' => 'root',
    'DB_ENV_MYSQL_PASSWORD' => '',
    'DATABASE_DSN' => 'mysql:host=localhost;port=3306;dbname=test',
    'DATABASE_USER' => 'root',
    'DATABASE_PASSWORD' => '',
    'DATABASE_TABLE_PREFIX' => '',
];

$_COOKIE = [
    'PHPSESSID' => 'efec57rgq0mb0iuej03ag2jul4',
    '_csrf' => 'adcc29e0230b25495de07b3683ecb41b117ef66e18cbca2022857334d869bb85s:32:"3p0ykYBVp-8_gQdCW2bZiWZYwJtaLnq1";',
];

$_SESSION = [
    '__flash' => [],
    '__captcha/site/captcha' => 'pzmaklq',
    '__captcha/site/captchacount' => 1,
    '__returnUrl' => '/hydra2/app/web/index.php?r=admin',
];

$_ENV = [
    'YII_DEBUG' => 'true',
    'YII_ENV' => 'dev',
    'YII_TRACE_LEVEL' => '',
    'APP_NAME' => '-------------',
    'APP_ADMIN_EMAIL' => '---------',
    'APP_ADMIN_PASSWORD' => 'admin',
    'APP_SUPPORT_EMAIL' => '-----------------',
    'APP_COOKIE_VALIDATION_KEY' => 'changeme2',
    'APP_COPYRIGHT' => '',
    'APP_PRETTY_URLS' => '',
    'DB_PORT_3306_TCP_ADDR' => 'localhost',
    'DB_PORT_3306_TCP_PORT' => '3306',
    'DB_ENV_MYSQL_DATABASE' => 'test',
    'DB_ENV_MYSQL_USER' => 'root',
    'DB_ENV_MYSQL_PASSWORD' => '',
    'DATABASE_DSN' => 'mysql:host=localhost;port=3306;dbname=test',
    'DATABASE_USER' => 'root',
    'DATABASE_PASSWORD' => '',
    'DATABASE_TABLE_PREFIX' => '',
];

**Comment by schmunk42** [comment]
This is a Windows problem, but I have no dev-machine to reproduce it right now.

Could you change...

```
preg_match('|(/[^/]/[^/].php)$|', FILE, $matches);
```

to

```
preg_match('|(\[^\]\[^\].php)$|', FILE, $matches);
```

And let me know if it works?

**Comment by carnao** [comment]
I changed that line but i got the same error.
For now i solved copying the files from app\vendor\dektrium\yii2-user\views to app\views\user. Under app\views\user there was no login.php.
Everithing seems to be running fine.
Thank you for your help!

**Comment by Konrad90** [comment]
fixed with https://github.com/phundament/app/pull/155

**Comment by undigo** [comment]
all works fine after these updates.
Thanks for all.
Your new admin interface is very nice than the older (p3)
Long live of Phundament !

**Comment by schmunk42** [comment]
@undigo You're welcome.
