### ISSUE TITLE
dockerfile composer.install

### ISSUE THREAD

**Issue by Quexer69** [phundament/app#150]
https://github.com/phundament/app/blob/master/Dockerfile#L5

`RUN /usr/local/bin/composer install --prefer-dist --dev --optimize-autoloader`

why do we use the option `--dev`. Apart from the fact that `--dev` is implied, shouldn't we use `--no -dev` ?

**Comment by schmunk42** [comment]
Using `--dev` is just to make it more clear what happens.

Since it wasn't possible to have two different Dockerfiles on the same level before Docker 1.5.0 we were not able to distinguish in a nice way between development and production - this should be fixed now.

Commit upcoming...
