### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by abolivar** [phundament/app#156]
I try and get this error

$./yii app/setup

Exception 'yii\base\InvalidConfigException' with message 'The configuration for the "user" component must contain a "class" element.'

xxxx/vendor/yiisoft/yii2/di/ServiceLocator.php:202

**Comment by abolivar** [comment]
the stack:
#0 xxxx/vendor/yiisoft/yii2/di/ServiceLocator.php(258): yii\di\ServiceLocator->set('user', Array)
#1 xxxx/vendor/yiisoft/yii2/base/Component.php(169): yii\di\ServiceLocator->setComponents(Array)
#2 xxxx/vendor/yiisoft/yii2/BaseYii.php(518): yii\base\Component->__set('components', Array)
#3 xxxx/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(yii\console\Application), Array)
#4 xxxx/vendor/yiisoft/yii2/base/Application.php(206): yii\base\Object->__construct(Array)
#5 xxxx/vendor/yiisoft/yii2/console/Application.php(79): yii\base\Application->__construct(Array)
#6 xxxx/yii(24): yii\console\Application->__construct(Array)
#7 {main}

**Comment by schmunk42** [comment]
Did you create your project with composer install or create-project?
The user module should be automatically bootstrapped.

You can add a class element to the user module in config/main.php as a workaround.

**Comment by abolivar** [comment]
I use composer create-project --stability=beta phundament/app and dont have any download error
