### ISSUE TITLE
Setup Error on 1und1 Server

### ISSUE THREAD

**Issue by philippfrenzel** [phundament/app#160]
´´´
--- begin chunk ---
[warning][yii\log\Dispatcher::dispatch] Unable to send log via yii\debug\LogTarget: Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Setting unknown property: yii\console\Request::cookieValidationKey' 

in /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/base/Component.php:197

Stack trace:
#0 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/BaseYii.php(518): yii\base\Component->__set('cookieValidatio...', 'fleurswithetfee')
#1 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/base/Object.php(105): yii\BaseYii::configure(Object(yii\console\Request), Array)
#2 [internal function]: yii\base\Object->__construct(Array)
#3 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/di/Container.php(372): ReflectionClass->newInstanceArgs(Array)
#4 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/di/Container.php(151): yii\di\Container->build('yii\\console\\Req...', Array, Array)
#5 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/BaseYii.php(344): yii\di\Container->get('yii\\console\\Req...', Array, Array)
#6 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/di/ServiceLocator.php(133): yii\BaseYii::createObject(Array)
#7 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/base/Application.php(536): yii\di\ServiceLocator->get('request')
#8 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2-debug/LogTarget.php(137): yii\base\Application->getRequest()
#9 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2-debug/LogTarget.php(51): yii\debug\LogTarget->collectSummary()
#10 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2-debug/LogTarget.php(112): yii\debug\LogTarget->export(Array)
#11 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/log/Dispatcher.php(183): yii\debug\LogTarget->collect(Array, true)
#12 /homepages/9/d202726989/htdocs/fleuretfee/ph-fleur-et-fee/vendor/yiisoft/yii2/log/Logger.php(170): yii\log\Dispatcher->dispatch(Array, true)
#13 [internal function]: yii\log\Logger->flush(true)
#14 {main}
[info][application] $_GET = [
    'yii' => ''
    'app/setup' => ''
]

--- end ---
´´´

**Comment by philippfrenzel** [comment]
Solved it, it's due to the fact that 1und1 doesn't support cli on a managed server :( So if you go to main.php in your config and before you execute yii in console, set the param if (cli...) to true... than it works out fine!

**Comment by schmunk42** [comment]
Thanks for providing the info.

Von meinem iPad gesendet
