### ISSUE TITLE
Dotenv load .env file return value

### ISSUE THREAD

**Issue by dungphanxuan** [phundament/app#164]
Hello, i trying to install app. I dump value on Dotenv load then receive value Null
This is code:
use \Dotenv;

$data =Dotenv::load(__DIR__.'/..');
var_dump($data);
die;

I thing it not success load .env file. and help me to fix it!
Thank!

**Comment by schmunk42** [comment]
Dotenv::load does not return a value, see https://github.com/vlucas/phpdotenv/blob/master/src/Dotenv.php#L18

Try dumping $_ENV, $_SERVER and use getenv('FOO_BAR') for accessing the values.

**Comment by dungphanxuan** [comment]
Hello, when i dumping $_ENV then recive value
array(19) {
  ["YII_DEBUG"]=>
  string(7) "true"
  ["YII_ENV"]=>
  string(5) "dev"
  .....

But call getenv('YII_DEBUG')  has return bool(false).
thanks!

**Comment by schmunk42** [comment]
Hmmmm, I don't see the error?!
Is this an issue with dotenv?

**Comment by dungphanxuan** [comment]
Hi @schmunk42 , I don't know what the error. I restart my computer and it run! Thank your!
