### ISSUE TITLE
Unable to install with docker-compose

### ISSUE THREAD

**Issue by Bogsey** [phundament/app#170]
When trying to install the application using `docker-compose run web composer create-project --prefer-dist` I get the following error

Cannot start container 49ced...: [8] System error: exec: "composer": executable file not found in $PATH

Any ideas?

**Comment by Bogsey** [comment]
Found the problem, was trying to run the command on the web container #171

**Comment by schmunk42** [comment]
btw: We're in the final stage with the stack, there'll be one more update before `rc1`, but it should not affect existing installations.

**Comment by philippfrenzel** [comment]
what does this mean? with the rc1

**Comment by schmunk42** [comment]
We finally found a stable setup for the application template :)
It covers development, testing, building and deployment - we're working on finishing the docs and code atm.
