### ISSUE TITLE
Admin Menu Collapses etc.

### ISSUE THREAD

**Issue by osCMattiFinn** [phundament/app#174]
The admin menu (multi level) collapses when you click anywhere on the page.

It should only collapse on page refresh or when you click the main menu item again, or click another menu item.

When you click a menu item and then click another menu item the first menu item clicked does not collapse.

This is one of the worst JS menus I have seen!

**Comment by schmunk42** [comment]
related https://github.com/dmstr/yii2-adminlte-asset/issues/23

@osCMattiFinn Any ideas about implementing this feature, eg. with cookies?

**Comment by osCMattiFinn** [comment]
I keep the menu open where it should be using Javascript.

I would like to see a solution for this issue:  The admin menu (multi level) collapses when you click anywhere on the page.

**Comment by philippfrenzel** [comment]
hmmm, maybe you should think about the sidebars extension - doesn't collapse by clicking somewhere else...

**Comment by osCMattiFinn** [comment]
I Googled "Phundament sidebars extension" and found nada.  Where is this to be found?

**Comment by philippfrenzel** [comment]
http://plugins.adchsm.me/slidebars/

**Comment by schmunk42** [comment]
fixed by https://github.com/dmstr/yii2-adminlte-asset/issues/63
