### ISSUE TITLE
Problem finalizing install

### ISSUE THREAD

**Issue by carnao** [phundament/app#178]
Hi i installed version 4 with composer on windows. When executing yii app/setup i get unknown command "app/setup".
Is there another method for installing this version applying migration and initialize the app?
Thanks!

**Comment by schmunk42** [comment]
Maybe a path issue?

What does `yii help` or `yii.bat help` say? (also `yii help app`?)

**Comment by carnao** [comment]
if I run the instructions above it gives me the correct help info. 
If i run yii help app i only get these actions:
clear-asset
create-mysq-db
generate-docs
setup-admin-user
version
And also if I run app/version i get this: 
"Application Version
Failed withouth error message: git describe --dirty"

Under dmstr\yii2-app-command\controllers the BaseAppController does not have a setup action and neither under src\commands the AppController .
On a previous install (don't know the exact version) under commands\AppController i had setup, setupTest, Update actions..

**Comment by schmunk42** [comment]
I think we need to update the docs here, since there's no more `app/setup` unless you have defined it in your application.

I was only a shorthand anyway for:

```
./yii app/create-mysql-db
./yii migrate --interactive=0
./yii app/setup-admin-user --interactive=0
```

see https://github.com/phundament/app/blob/master/src/init.sh

Can you run the commands manually or create an `init.bat`?

**Comment by carnao** [comment]
Sorry for the delay..
That's ok I just ran the command manually and all was ok!
Thanks!
