### ISSUE TITLE
Update composer installed phundament

### ISSUE THREAD

**Issue by danielblues** [phundament/app#183]
Hi,
 How can I update a composer installed phundament?
 I've used this instructions to install it:
https://github.com/phundament/app/blob/master/docs/alternatives/20-installation-composer.md
 Thank you
Daniel

**Comment by Quexer69** [comment]
Hi Daniel,

just run in your project root 'composer install'

This will update your composer packages to the version constraints given in your project composer.json.

Hope thats what you are looking for.

Cheers Chris

**Comment by danielblues** [comment]
Hi,
 Thank you for your quick answer, i've run 'composer install' and got the same answer as 'composer update' 
 composer.json is one of the files I want to see updated.

```
  "require-dev": {
    "dmstr/yii2-cms-dev-metapackage": "dev-master",
    "dmstr/yii2-libs-metapackage": "dev-master",
    "dmstr/yii2-yaml-converter-command": "dev-master",
    "yiisoft/yii2-debug": "@stable",
    "schmunk42/yii2-giiant": "dev-master#d40733b"
  },
```
is now: 
```
    "require-dev": {
     "dmstr/yii2-cms-dev-metapackage": "@stable",
     "dmstr/yii2-libs-metapackage": "@stable",
     "yiisoft/yii2-debug": "@stable",
     "schmunk42/yii2-giiant": "0.5.*"
  },
```
Thanks again

**Comment by Quexer69** [comment]
Sorry Daniel -> `composer update`

**Comment by danielblues** [comment]
Hi,
 I'm going to assume by the silence that it's not an supported update path.
 I will give docker a try.
Daniel

**Comment by schmunk42** [comment]
@danielblues You can update your packages in Phundament by using the standard composer commands. If you'd like to stay on `dev-master` for a package use either

 - update `composer.json` and run `composer update` 
 - or run `composer require vendor/package:dev-master`

The default packages in Phundament just have rather strict constraints, because less things tend to break then.

**Comment by danielblues** [comment]
That worked.
Thank you.
