### ISSUE TITLE
Documents not displaying correctly from website

### ISSUE THREAD

**Issue by dgleba** [phundament/app#188]
When I click the docs button on the  http://phundament.com it displays 

```
phundament.com Docs Contact Signup Login Error (#2) An internal server error occurred.
```

I pressed the following button which goes to this address...

http://phundament.com/docs/10-about.md

![image](https://cloud.githubusercontent.com/assets/4622715/11532088/5cf77802-98cf-11e5-8f93-3ca4a1cdb09f.png)

It seems the other docs button in the navbar doesn't seem to work well either.

Can someone comment?

**Comment by schmunk42** [comment]
Thank you for reporting, I need to fix this ASAP.

**Comment by schmunk42** [comment]
Moved docs to a new repo: https://github.com/phundament/docs
