### ISSUE TITLE
Error 255: require(/app/src/config/assets-gen/prod.php): failed to open stream

### ISSUE THREAD

**Issue by philippfrenzel** [phundament/app#191]
![image](https://cloud.githubusercontent.com/assets/2319890/11877996/3303c840-a4f3-11e5-960a-6f63fa456780.png)

**Comment by philippfrenzel** [comment]
after make all

**Comment by schmunk42** [comment]
Which version are you using?
Is the file there on your host an in the container?
Could you post a bit more of the output...

**Comment by philippfrenzel** [comment]
Just pulled today the version:

4.0.0-dev

and then tried to "just make" "make all" -> my other phundament setups work fine, so don't know why this one doesnt like e

**Comment by schmunk42** [comment]
This may be related to `docker-compose` and override files.
Which version do you have, can you upgrade to 1.5.2?

Workaround: Set `YII_ENV` to `dev` in `.env`.

**Comment by philippfrenzel** [comment]
1.4.2 and I try to update - thanks!

**Comment by philippfrenzel** [comment]
ok, can confirm that after update to docker-compose 1.5.2 everything works perfect!
Thanks for support!
