### ISSUE TITLE
Phundament with postgres db.

### ISSUE THREAD

**Issue by akaSStalkALEX** [phundament/app#195]
Is there any opportunity to have another version based on postgres image instead of mariadb?
In no case I am not so proficient in Docker, so I could use a little help to make it by myself.

**Comment by schmunk42** [comment]
It's on my list since a while, but I never had the time to work on it.

Basically you need to replace the MySQL image with a Postgres and adjust the driver in the config.
There may also smaller glitches ahead with the DB and user setup and migrations, but the template is prepared to handle that.

Here's just a quick-shot: https://github.com/phundament/app/tree/feature/postgres

We need to fix `yii2-pages`, as a workaround disable it's migrations https://github.com/dmstr/yii2-pages-module/blob/master/Bootstrap.php#L30

**Comment by akaSStalkALEX** [comment]
Thanks, It's working quite smoothly with postgres db. But I rewrote migration you've mentioned. Here's my version, not sure if it's super correct. https://gist.github.com/akaSStalkALEX/b4c19869e974de226bfc

**Comment by schmunk42** [comment]
Nice! Thank you, will try to merge this ASAP.

One more thing, ... currently there's a MySQL CLI controller registered in the application, see
 - https://github.com/dmstr/yii2-db#dmstrconsolecontrollersmysqlcontrollers
 - https://github.com/dmstr/yii2-db/blob/master/console/controllers/MysqlController.php

I don't know if you need to create a Postgres version for it. If the image supports user setup and you're fine with it - perfect.

It's in use here: https://github.com/phundament/app/blob/master/src/setup.sh#L9 - maybe you also have to remove it. But it's definitely a goal to make the template database agnostic.

Would also be great if you could give https://github.com/schmunk42/yii2-giiant a try with Postgres ;)

**Comment by akaSStalkALEX** [comment]
Yes, forgot to mentioned it :) I turned off db creating too and created db manually. Giiant is working quite alright too. We are using it from backend for creating models and haven't see any serious problems yet. 
One thing - show difference is not working, when model, for example, was recreated.

**Comment by schmunk42** [comment]
> One thing - show difference is not working, when model, for example, was being recreated.

CLI or Web UI? Did you enable `--crudTidyOutput`?

PS: Thanks for the feedback, good to hear.

**Comment by akaSStalkALEX** [comment]
I used Web UI. After "diff" button has clicked, another page is shown with error message "File has not been found *some hash here*". I could make screenshot later if you need.

**Comment by schmunk42** [comment]
Would be really helpful, maybe it's the best just to create an issue at giiant's repo.

**Comment by schmunk42** [comment]
@akaSStalkALEX Just FYI, I refactored yii2-pages migrations: https://github.com/dmstr/yii2-pages-module/commit/2c987afa2e54c0e1850932d5617dae393fe11676

Not released yet.

**Comment by akaSStalkALEX** [comment]
@schmunk42 Hey) Thank you very much!

**Comment by schmunk42** [comment]
### Current status

On top of https://github.com/phundament/app/tree/feature/postgres - you need to uncomment this line in `src/setup.sh`

    #./yii db/create

I think about removing that line and adding it to a manual setup setup step, but I am not fully decided yet.

Moreover you need these aliases in `composer.json`

    "dektrium/yii2-user": "dev-master as 0.9.5.99",
    "dmstr/yii2-pages-module": "dev-feature/compose-v2 as 0.12.0",

I think we can release 0.12.0 for *pages*, but we'll need to wait for dektrium for a new *yii2-user* release.

I'll keep this issue open until then.

**Comment by schmunk42** [comment]
I've added this here: https://github.com/phundament/docs/blob/master/6-tutorials/database.md#using-a-postgresql-database
