### ISSUE TITLE
Use net instead of link

### ISSUE THREAD

**Issue by sum1190** [phundament/app#199]
Hi,

Is it possible use `net` instead of `link` in Phundament to let container comunicate in docker-compose? I've read that link will be deprecated soon, maybe it will change the way the container are linked to each others?

**Comment by schmunk42** [comment]
Yes, I plan to update this.

Here's an [example](https://github.com/dmstr/yii2-prototype-module/blob/master/tests/docker-compose.yml) how a Phundament app works with networking and without links (needs to be adjusted a bit for phundament/app)

**Comment by sum1190** [comment]
Ok, so I can consider this issue closed. Thank you!

**Comment by schmunk42** [comment]
See the commit above for a first draft, but we're having some issues with it (https://github.com/docker/docker/issues/21168).

Would be great if you could give feedback, if you're also having this problem or not.
