### ISSUE TITLE
Cleaner way to override admin layout for user module

### ISSUE THREAD

**Issue by david-sa** [phundament/app#206]
It seems that the reason of [these files](https://github.com/phundament/app/tree/4.3.0-rc1/src/views/user/admin) is just to apply `@app/views/layouts/box` to the admin section of the user module.

As you can read [here](https://github.com/dektrium/yii2-user/issues/155#issuecomment-60927409), a cleaner way to achieve it is by updating the controller map:

```
        'user' => [
            ...
            'controllerMap' => [
            	'admin' => [
            		'class' => 'dektrium\user\controllers\AdminController',
            		'layout' => '@admin-views/layouts/box',
            	],
            ],
        ],
```
If the development of _phd4_ is already over, maybe you can have it in mind for _phd5_. 
(**Edit**: I just saw that in _phd5_ you are using a different approach)

**Comment by schmunk42** [comment]
Thank you! That's also a nice solution.
I was using dependency injection, like so:

```
Yii::$container->set(
    'dektrium\user\controllers\AdminController',
    [
        'layout' => '@backend/views/layouts/box'
    ]
);
```

btw: phd4 and phd5 are not very different, the main difference is that phd5 has much less code :)

**Comment by david-sa** [comment]
Thank you for the info!

I think I can close this one.
