### ISSUE TITLE
cron can't access db

### ISSUE THREAD

**Issue by philippfrenzel** [phundament/app#209]
# Phundament 4 - Local development overrides

version: '2'
services:
  php:
    volumes:
      - .:/app
    environment:
      - YII_ENV=dev
      - YII_DEBUG=1
      - DB_PORT_3306_TCP_ADDR=db
      - DB_PORT_3306_TCP_PORT=3306
      - DB_ENV_MYSQL_ROOT_USER=root
      - DB_ENV_MYSQL_ROOT_PASSWORD=secretadmin
  nginx:
    ports:
      - '40080:80'
    volumes:
      - .:/app
  cron:
    build: .
    depends_on:
      - php
    mem_limit: 128m
    restart: always
    volumes:
      - .:/app
    links:
      - 'db:percona'
    command: >
      /bin/bash /usr/bin/start-cron.sh
  db:
    ports:
      - '3306:3306'
  appratchetcall:
    ports:
      - '8004:8004'
    volumes:
      - .:/app

Error from within container:

Error: SQLSTATE[HY000] [2002] No such file or directory

as it looks like no connection to the db is possible

**Comment by schmunk42** [comment]
Check the logs of the db container, it looks like it's not up and running.

Please reopen if the problem persists.
