### ISSUE TITLE
Include compatible version of codeception in require-dev or documentation

### ISSUE THREAD

**Issue by motin** [phundament/app#91]
Had issues with running codeception as per the wiki instructions https://github.com/phundament/app/wiki/Testing:
   
```
$ php codecept.phar run -c`pwd`
Codeception PHP Testing Framework v1.7.1
Powered by PHPUnit 3.7.27 by Sebastian Bergmann.
[Thu Oct 24 00:33:35 2013] ::1:49964 [500]: /index-test.php

Fatal error: Call to undefined method Codeception\Scenario::condition() in /Users/motin/Dev/Projects/Gapminder/gapminder-school-product/phundament-pristine/app/tests/codeception/acceptance/WebGuy.php on line 245
```

It seems that the tests do not work with the latest codeception. Please include a verified version of codeception in require-dev or mention it in the docs so that we can install a version that works with phundament tests.

Running the following makes tests run again without fatal errors:

```
php composer.phar require "codeception/codeception:1.6.2" 
vendor/codeception/codeception/codecept run -c`pwd` 
```

(the tests fail, but that's another issue)

**Comment by schmunk42** [comment]
For Phundament 4 testing is now available via Docker & fig  in separate contianers, see https://github.com/phundament/app/blob/master/docs/42-testing.md#running-in-isolated-docker-containers for details
